name: Trigger alspac-shiny to rebuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call alspac-shiny
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        EVENT: r-alspac-update
        ORG: explodecomputer
        REPO: alspac-shiny
      run: |
        curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${PAT_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"