name: Trigger ALSPAC Shiny Build

on:
  push:
    branches:
      - main
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: explodecomputer/alspac-shiny
          event-type: rebuild-docker
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
